LOCK STEERING TO SHIP:PROGRADE.
WAIT UNTIL ETA:APOAPSIS < 7.
LOCK THROTTLE TO 1.
WAIT UNTIL SHIP:OBT:PERIAPSIS > 125000.
LOCK THROTTLE TO 0.05.
WAIT UNTIL SHIP:OBT:PERIAPSIS > 150000.
LOCK THROTTLE TO 0.